# Generated by Django 4.1 on 2022-08-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_medicine_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='medicine',
            table='medicine',
        ),
    ]
