# Generated by Django 4.0.5 on 2022-07-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_status_priscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priscription',
            name='quantity',
        ),
    ]
