# Generated by Django 4.0.6 on 2022-07-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_medicine_price'),
        ('appointment', '0003_remove_priscription_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Priscription',
            new_name='Prescription',
        ),
    ]
