# Generated by Django 4.0.6 on 2022-08-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_unique_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ct',
            field=models.ImageField(blank=True, null=True, upload_to='images/ct'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test_report',
            field=models.FileField(blank=True, null=True, upload_to='files/report'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='xray',
            field=models.ImageField(blank=True, null=True, upload_to='images/xray'),
        ),
    ]
