# Generated by Django 4.0.6 on 2022-08-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_ct_appointment_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ct',
            field=models.FileField(blank=True, null=True, upload_to='images/ct'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='xray',
            field=models.FileField(blank=True, null=True, upload_to='images/xray'),
        ),
    ]
