# Generated by Django 4.0.6 on 2022-08-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_appointment_ct_alter_appointment_xray'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'start_time']},
        ),
    ]
