# Generated by Django 4.0.6 on 2022-08-25 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_appointment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='ct',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='test_report',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='xray',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_report', models.FileField(blank=True, null=True, upload_to='files/report')),
                ('xray', models.FileField(blank=True, null=True, upload_to='images/xray')),
                ('ct', models.FileField(blank=True, null=True, upload_to='images/ct')),
                ('diagnosis', models.TextField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='appointment.appointment')),
            ],
        ),
    ]
