# Generated by Django 4.1 on 2022-08-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_alter_report_ct_alter_report_test_report_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['appointment__date', 'appointment__start_time']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['appointment__date', 'appointment__start_time']},
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
        migrations.AlterModelTable(
            name='prescription',
            table='prescription',
        ),
        migrations.AlterModelTable(
            name='report',
            table='report',
        ),
    ]
