# Generated by Django 4.0.5 on 2022-07-04 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_alter_patientprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'P'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patprofile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
