# Generated by Django 4.0.5 on 2022-07-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('profiles', '0007_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
