# Generated by Django 4.0.6 on 2022-08-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_medicine_price'),
        ('profiles', '0008_delete_medicine_alter_doctorprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.department'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_pic',
            field=models.ImageField(upload_to='images/profiles/doctors'),
        ),
    ]
